[WIP]chat-spaceのビュー画面の作成
kaitomdion/chat-space pull request #3
Opened 2019-05-26 08:33 UTC by kaitomdion

# WHAT
chat-spaceのビュー画面の作成のため

# WHY
Hamlでマークアップができるようにするため
BEMを利用した命名ができるようにするため
Sassでスタイルが書けるようにするため

2019-05-26 08:37 UTC, nagatomokent commented on app/views/layouts/mailer.html.haml
> +    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
ハッシュロケットは使わないようにしましょう

2019-05-26 08:37 UTC, nagatomokent commented on app/assets/stylesheets/application.scss
> +@import "variable";
application.scssは@importのみで他のcssは書かないよにしましょう

2019-05-26 08:37 UTC, nagatomokent commented on app/controllers/messages_controller.rb
> +def index
インデント修正してください

2019-05-26 08:37 UTC, nagatomokent commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケット使わないようにしましょう

2019-05-26 09:31 UTC, kaitomdion commented
修正しました。

2019-05-26 10:36 UTC, ghost requested changes

2019-05-26 10:36 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +  .footer
formタグを使って書いた方がいいかと思います。

2019-05-26 10:36 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +          %a{href: "#"}
link_toで仮置きしましょう

2019-05-26 10:36 UTC, hiroki5123 commented on app/views/messages/index.html.erb
> +<p>Hello World!</p>
削除しましょう

2019-05-26 11:11 UTC, kuroko918 commented on app/views/layouts/mailer.html.haml
> +    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
こちら修正お願いします。

2019-05-26 11:11 UTC, kuroko918 commented on app/views/messages/index.html.erb
> +<p>Hello World!</p>
こちら消して下さい。

2019-05-26 11:11 UTC, kuroko918 commented on app/views/messages/index.html.haml
> +  .footer
こちら如何ですか？

2019-05-26 11:11 UTC, kuroko918 commented on app/views/messages/index.html.haml
> +    %a.top__edit-box{href: "#"} Edit
aタグではなく、link_toを使いましょう！

2019-05-26 11:11 UTC, kuroko918 commented on app/views/messages/index.html.haml
> +    %a.top__edit-box{href: "#"} Edit
他も変更お願いします

2019-05-27 01:50 UTC, kaitomdion commented on app/views/messages/index.html.haml
> +    %a.top__edit-box{href: "#"} Edit
全て変更しました。

2019-05-27 02:11 UTC, TOMARUMARU commented on app/views/layouts/mailer.html.haml
> +    = yield
mailer系のファイルは使用しないので、削除して大丈夫です

2019-05-27 02:11 UTC, TOMARUMARU commented on app/views/layouts/mailer.text.haml
> += yield
mailer系のファイルは使用しないので、削除して大丈夫です

2019-05-27 02:11 UTC, TOMARUMARU commented on config/routes.rb
> +  get 'messages' => 'messages#index'
root_pathに設定しましょう

2019-05-27 02:29 UTC, kaitomdion commented on app/views/layouts/mailer.html.haml
> +    = yield
削除しました。

2019-05-27 02:29 UTC, kaitomdion commented on app/views/layouts/mailer.text.haml
> += yield
削除しました。

2019-05-27 02:33 UTC, kaitomdion commented on config/routes.rb
> +  get 'messages' => 'messages#index'
設定しました。

2019-05-27 02:36 UTC, miyagit commented on app/views/layouts/mailer.html.haml
> +!!!
mailer系のファイルは削除しましょう。

2019-05-27 02:39 UTC, kaitomdion commented on app/views/layouts/mailer.html.haml
> +!!!
削除しました。

2019-05-27 02:41 UTC, miyagit commented on app/views/messages/index.html.haml
> +  .footer
こちらについてはどうですか？

2019-05-27 02:51 UTC, miyagit approved these changes
LGTM

2019-05-27 04:49 UTC, merged